# Dockerfile.nginx
FROM nginx:latest

# Copie des fichiers de configuration et HTML dans le conteneur
COPY nginx_conf/nginx.conf /etc/nginx/conf.d/default.conf
COPY nginx_html/index.html /usr/share/nginx/html/index.html
