name: Docker Compose CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker
        uses: docker/setup-docker@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull existing Docker images
        run: docker compose -f docker-compose-postgis-geoserver.yml pull

      - name: Build and Start Docker Compose Services
        run: |
          docker compose -f docker-compose-postgis-geoserver.yml build --no-cache
          docker compose -f docker-compose-postgis-geoserver.yml up -d

      - name: Wait for services to be ready
        run: |
          for i in {1..30}; do
            if docker compose -f docker-compose-postgis-geoserver.yml ps | grep 'Up'; then
              echo "Services are up and running!"
              break
            else
              echo "Waiting for services to be ready..."
              sleep 10
            fi
          done

      - name: Check database schema and tables
        run: |
          docker compose -f docker-compose-postgis-geoserver.yml exec -T postgis psql -U gis -d gis -f /Ressources/check_db.sql

      - name: Wait for GeoServer to be fully initialized
        run: |
          for i in {1..30}; do
            curl -s --head --request GET http://localhost:8080/geoserver/web/?page=login | grep "200 OK" && break
            echo "Waiting for GeoServer to be fully initialized..."
            sleep 10
          done

      - name: Run curl test
        run: |
          curl -f 'http://localhost:8080/geoserver/espace/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=espace%3ABretelles&maxFeatures=50&outputFormat=application%2Fjson'

      - name: Shut down services
        run: docker compose -f docker-compose-postgis-geoserver.yml down

      - name: Push Docker Images to Docker Hub
        run: docker compose -f docker-compose-postgis-geoserver.yml push
